default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: gamepay_development
test:
  <<: *default
  database: gamepay_test
production:
  url: <%= ENV['DATABASE_URL'] %>
